# Site information
site_name: Declo
site_author: Arun Patro
site_url: https://arunpatro.github.io/declo
site_description: Declo is a python with javascript like functional syntax.

# Repository
repo_name: arunpatro/declo
repo_url: https://github.com/arunpatro/declo

# Copyright
copyright: Copyright &copy; 2025 - Arun Patro

# Configuration
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  font:
    text: Inter
    code: Source Code Pro
  palette:
    # scheme: slate
    primary: 'black'
    accent: 'indigo'
  features:
    - content.code.copy
    - navigation.expand
    # - navigation.tabs
    - navigation.sections
    # - header.autohide
    - announce.dismiss

# Extensions
markdown_extensions:
  # - admonition
  - def_list
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      noclasses: True
      pygments_style: default
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.inlinehilite
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg