[project]
name = "declopy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "astor>=0.8.1",
    "fire>=0.7.0",
    "pydantic>=2.10.4",
    "structlog>=24.4.0",
]

[project.scripts]
declopy = "declopy.cli:main"

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
]

[build-system]